{% set name = "sphinxcontrib-mermaid" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib-mermaid-{{ version }}.tar.gz
  sha256: 75ba8ab66b5157864360f5654a335af4a78384d5e9659c8d8e9ec9601d0a81b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sphinx
    - docutils

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ericpre
