{% set name = "sphinxcontrib-mermaid" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgaitan/sphinxcontrib-mermaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: 824f90ba951c380a3b991b3435a42cbc2972e20aa5dd1b8e0788128ee688e759

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - jinja2
    - sphinx
    - pyyaml

test:
  source_files:
    - tests
  imports:
    - sphinxcontrib
    - sphinxcontrib.mermaid
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # missing myst_parser
    - pytest -vv --deselect=tests/test_html.py::test_html_raw_from_markdown tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericpre
