{% set name = "sphinxcontrib-mermaid" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgaitan/sphinxcontrib-mermaid/archive/refs/tags/0.7.tar.gz
  sha256: 014a1173d68b15298277b08b082117c5a7ea0765531b79e3aa20044080dd0b0c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sphinx
    - docutils

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ericpre
