{% set name = "sphinxcontrib-mermaid" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgaitan/sphinxcontrib-mermaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2db8acffae485e73368122f6e31b7d5a87d70ccd5b1ab80d588fc312bb61f219

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - sphinx
    - docutils

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ericpre
