{% set name = "sphinxcontrib-mermaid" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgaitan/sphinxcontrib-mermaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: 824f90ba951c380a3b991b3435a42cbc2972e20aa5dd1b8e0788128ee688e759

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - sphinx
    - docutils

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ericpre
